parameters:
  - name: agentPool
    type: string
    default: Azure Pipelines
    values:
      - "Azure Pipelines"
      - "Slovink-Selfhosted-Agent"

trigger:
  - main

variables:
  - name: gcp_bucket
    value: slovink-hyperscaler
  - name: terraformVersion
    value: 1.9.5
  - name: authenticationFileName
    value: slovink-hyperscaler.json
  - name: projectName
    value: "Slovink hyperscaler"
  - name: projectId
    value: "slovink-hyperscaler"
  - name: platformName
    value: "google"
  - name: environment
    value: "development"
  - name: region
    value: "us-east1"
  - name: zone
    value: "us-east1-b"
  - name: agentPoolName
    value: ${{ parameters.agentPool }}

pool:
  name: $(agentPoolName)

stages:
  - stage: Prepare
    displayName: Initialization
    jobs:
      - job: prepare
        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: $(terraformVersion)

          - script: |
              rm -rf *
            displayName: Clean workspace

          - task: DownloadSecureFile@1
            name: development
            displayName: Get GCP Secrets
            inputs:
              secureFile: $(authenticationFileName)

          - script: |
              cp $(development.secureFilePath) $(System.DefaultWorkingDirectory)/$(authenticationFileName)
            displayName: Copy secrets file to workspace

  - stage: service_account
    dependsOn: Prepare
    displayName: Service Account Provisioning
    jobs:
      - job: service_account
        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: $(terraformVersion)

          - script: |
              echo "Setting GOOGLE_APPLICATION_CREDENTIALS env var"
              export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/$(authenticationFileName)
              echo "export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/$(authenticationFileName)" >> $BASH_ENV
            displayName: Export GOOGLE_APPLICATION_CREDENTIALS

          - task: TerraformCLI@0
            displayName: Terraform Initialize
            inputs:
              command: init
              workingDirectory: $(System.DefaultWorkingDirectory)/examples/multiple_service_accounts
              backendType: gcs
              backendGcsCredentials: $(authenticationFileName)
              backendGcsBucket: $(gcp_bucket)
              backendGcsPrefix: $(projectId)/$(platformName)/network.infrax.tfstate

          - task: TerraformCLI@0
            displayName: Terraform Plan
            inputs:
              provider: 'google'
              command: 'plan'
              workingDirectory: $(System.DefaultWorkingDirectory)/examples/multiple_service_accounts
              environmentServiceNameGCP: 'Your-GCP-Service-Connection-Name'
              commandOptions: '-var-file="$(System.DefaultWorkingDirectory)/terraform.tfvars"'

          - task: TerraformCLI@0
            displayName: Terraform Apply
            inputs:
              provider: 'google'
              command: 'apply'
              workingDirectory: $(System.DefaultWorkingDirectory)/examples/multiple_service_accounts
              environmentServiceNameGCP: 'Your-GCP-Service-Connection-Name'
              commandOptions: '-var-file="$(System.DefaultWorkingDirectory)/terraform.tfvars"'
